# Generated by Django 4.0.3 on 2022-04-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_chapter', models.CharField(max_length=100, null=True, verbose_name='最后阅读章节')),
                ('last_read_time', models.DateTimeField(auto_now=True, verbose_name='最后阅读时间')),
                ('last_read_url', models.CharField(max_length=500, null=True, verbose_name='最后阅读章节的链接')),
                ('is_read', models.SmallIntegerField(default=0, verbose_name='是否浏览')),
                ('collect', models.SmallIntegerField(choices=[(0, '未加入书架'), (1, '已加入书架')], default=0, verbose_name='是否收藏')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book', verbose_name='小说id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='用户id')),
            ],
            options={
                'db_table': 'book_history',
            },
        ),
    ]
