# Generated by Django 4.0.3 on 2022-04-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bookhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.CharField(max_length=200, verbose_name='漫画名'),
        ),
    ]
